UserReactivated: Uživatel reaktivován
UserUnknown: Uživatel neznámý
UserOrArticleUnknown: Uživatel nebo zboží neznámé
PurchaseSuccess: Dobrou chuť!
PurchaseDebtful: Pozor: Jsi v dluhu!
NotEnoughItems: Není dost zboží dostupné
ErrorOccured: Něco se pokazilo
ItemUnknown: Zboží neznámé
PurchaseSuccessCash price@Int currency@Text: Dobrou chuť. prosím zaplať #{currency} #{formatIntCurrency price} #{currency} v hotovosti.
ItemDisappeared: Zboží zmizelo o_0
Amount: Počet
EditSuccess: Změna úspěšná
EditFail: Změna se nezdařila
Name: Jméno
Price: Cena
CurrentStock: Aktuální stav
AnnouncedStock: Oznamovací počet
DeleteItem: Smazat zboží
ItemDeleted: Zboží smazáno
UserCreated: Uživatel vytvořen
UserNotCreated: Nemohl jsem vytvořit uživatele
EmailNotify: Vlož Email zda si přeješ správy
BuyNotification: Notify on purchase
UserEdited: Uživatel změněn
UserNotEdited: Nemohl jsem změnit uživatele
Payout desc@Text: Výplata: #{desc}
PaidOut: Častka vyplacena
NotPaidOut: Nemohl jsem vyplatit
Value: Cena
Description: Popis
StockedUp: Nabral jsem zásoby
NotStockedUp: Nemohl jsem nabrat zásoby
StockupError: Chyba při nabírání zásob
AmountAdded: Množství přidáno
ItemAdded: Nový zboží přidáno
ItemNotAdded: Chyba při přidávání
AmountWarning: Výstraha počtu
Recharged: Znovu nabyto!
RechargeError: Chyba při nabíjení
CashCheck: Inspekce kasy
CashChecked: Kasa kontrolována a aktualizována.
CashCheckError: Chyba při inspekce kasy
CountedValue: Hotovost
PurchaseOf name@Text: Koupě of #{name}
PricePerUnit price@Int currency@Text: Cena za kus: #{currency} #{formatIntCurrency price}
Purchase: Koupit
PleaseCountAndCheck: Spočítej Hotovost a zadej ji v poli dole
Submit: Odeslat
Home: Domů
Restock: Přidat zásoby
Journal: Žurnál
Summary: Inventář
PayCash: Platit v hotovosti
CreateUser: Vytvořit uživatele
ReactivateOldUser: Reaktivovat starého uživatele
Time: Čas
ValueIn currency@Text: Cena v #{currency}
TotalValue: Celkový obnos
CashStock: Hotovost
PayoutFromCash: Vyplatit
NothingToShow: Žadné pohyby v kase
NewItem: Nový zboží
NewUser: Nový uživatel
DoPayout: Vyplatit
ReactivateUser: Reaktivovat uživatele
Recharge: Znovu nabít
CurrentCharge charge@Int currency@Text: Aktualní kredit: #{currency} #{formatIntCurrency charge} #{currency}
AddItem: Přidat Zboží
EditUser: Editovat uživatele
ChoosePrompt text@Text: Vyber si, #{text}
SelectItem: Vybrat zboží
CurrentAmount: Aktuální počet
NoItems: Žadné zboží
StockUp name@Text: Přidat #{name}
Fillup: Naplnit
CashCheckOf date@String: Kontrola kasy od #{date}
NotJson: Toto nejsou JSON data
Upload: Nahrát zálohu
SelectFile: Vyber soubor
RestoreSuccess: Databáze znovu nahrána!
InventoryBackup: Stahnout zálohu
RestoreFromBackup: Nahrát záĺohu
NegativeRecharge: Nelze nabít negativní obnos
Increment: ++
Decrement: --
Plus5: +=5
Minus5: -=5
SelectAvatar: Vyber avatar
Avatars: Avatary
NoAvatars: žádné avatary
ModifyAvatar: Modify avatar
AvatarUnknown: Avatar neznámý
AvatarUpdateSuccessfull: Aktualizace avataru se zdařila
AvatarIdent: Jméno avataru
AvatarFileChange: Zadej soubor k změnně avataru
AvatarFile: Soubor avataru
NewAvatar: Nový avatar
AvatarUploadSuccessfull: Avatar úspěšně nahrán
DeleteAvatar: Smazat avatar
AvatarDeleted: Avatar úspěšně smazán
AvatarInUseError: Avatar nelze smazat dokud je v užitku
Volume: Objem v l
CorrectedAmount: Stráta
BarcodeNotUser: Tento kód není pro uživatele, ale pro produkt
ProvideBarcode: Prosím zadej správný kód
BarcodeNotBev: Tento kód není pro produkt, ale pro uživatele
BarcodeUnknown: Tento kód je neznámý
BarcodeField: Čárový kódy
BarcodeAdded: Kód zadán
BarcodeDuplicate: Tento kód se již používá
Transfer: Převod
TransferTo: Převést kredit na
NegativeTransfer: Nelze převést negativní počty
TransferComplete: Převod dokončen
TransferError: Chyba při převodu
PreviousPage: předchozí strana
NextPage: další strana
MaxAmount: Maximální počet v zásobě
AmountPerCrate: Počet v Přepravce
SelectSupplier: Vyber dodavatele
CreateSupplier: Vytvoř dodavatele
SupplierCreated: Dodavatel vytvořen
SupplierNotCreated: Dodavatel nevytvořen!
Suppliers: Dodavatele
NewSupplier: Nový dodavatel
Address: Adresa
TelNr: Telefonní číslo
Email: Email
EditSupplier: Uprav Dodavatele
SupplierUnknown: Dodavatel neznámý!
SupplierEdited: Dodavatel byl upraven
SupplierNotEdited: Dodavatel nebyl upraven!
CreateSupplierDigest: Vytvoř přehled objednávky u tohoto dodavatele
DeleteSupplier: Vymaž Dodavatele
SupplierDeleted: Dodavatel vymazán
SupplierInUseError: Tento dodavatel se stále používá
ArtNr: Kód zboží
PricePerCrate: Cena za přepravku
CrateCount: Počet Přepravek
BuyValue: K placení
CustomerId: Kód zákazníka
TotalCrates: Celkový počet přepravek
Modify: upravit
UserIdentNotUnique: Uživatelské jméno není jedinečný
