UserReactivated: Nutzer reaktiviert
UserUnknown: Nutzer unbekannt
UserOrArticleUnknown: Benutzer oder Artikel unbekannt
PurchaseSuccess: Viel Vergnügen
PurchaseDebtful: Achtung: Guthaben im negativen Bereich
NotEnoughItems: So viele Artikel sind nicht vorhanden
ErrorOccured: Etwas ist schief gelaufen
ItemUnknown: Artikel unbekannt
PurchaseSuccessCash price@Int currency@Text: Viel Vergnügen. Bitte Zahle #{formatIntCurrency price} #{currency} in die Kasse ein
ItemDisappeared: Artikel ist verschwunden o_0
Amount: Anzahl
EditSuccess: Bearbeitung erfolgreich
EditFail: Bearbeitung nicht möglich
Name: Name
Price: Preis
CurrentStock: Aktueller Bestand
AnnouncedStock: Meldebestand
DeleteItem: Artikel löschen
ItemDeleted: Artikel gelöscht
UserCreated: Benutzer angelegt
UserNotCreated: Benutzer konnte nicht angelegt werden
EmailNotify: E-Mail eintragen falls Benachrichtigungen erwünscht
BuyNotification: Benachrichtigung bei Kauf
UserEdited: Nutzerdaten aktualisiert
UserNotEdited: Nutzerdatenaktualisierung nicht erfolgreich
Payout desc@Text: Auszahlung: #{desc}
PaidOut: Betrag ausgezahlt
NotPaidOut: Auszahlung nicht möglich
Value: Betrag
Description: Beschreibung
StockedUp: Bestand aufgefüllt
NotStockedUp: Bestand kann nicht negativ aufgefüllt werden
StockupError: Fehler beim Auffüllen
AmountAdded: Anzahl hinzugefügt
ItemAdded: Neuer Artikel hinzugefügt
ItemNotAdded: Fehler beim Hinzufügen
AmountWarning: Warnung bei Anzahl
Recharged: Guthaben erfolgreich aufgeladen
RechargeError: Fehler beim Aufladen
CashCheck: Kassensturz
CashChecked: Kassensturz durchgeführt. Kasse aktualisiert
CashCheckError: Fehler im Kassensturz
CountedValue: Gezählter Betrag
PurchaseOf name@Text: Kauf von #{name}
PricePerUnit price@Int currency@Text: Preis pro Einheit: #{formatIntCurrency price} #{currency}
Purchase: Kaufen
PleaseCountAndCheck: Bitte Kasse zählen und gezählten Betrag in unten stehendes Feld eintragen.
Submit: Absenden
Home: Nachhause
Restock: Lager befüllen
Journal: Journal
Summary: Inventar
PayCash: Bar bezahlen
CreateUser: Neuen Nutzer anlegen
ReactivateOldUser: Alten Nutzer reaktivieren
Time: Zeit
ValueIn currency@Text: Betrag in #{currency}
TotalValue: Gesamtbetrag
CashStock: Kassenbestand
PayoutFromCash: Aus der Kasse auszahlen
NothingToShow: Noch keine Bewegungen zu verzeichnen
NewItem: Neuer Artikel
NewUser: Neuer Benutzer
DoPayout: Auszahlen
ReactivateUser: Nutzer reaktivieren
Recharge: Guthaben aufladen
CurrentCharge charge@Int currency@Text: aktuelles Guthaben: #{formatIntCurrency charge} #{currency}
AddItem: neuen Artikel hinzufügen
EditUser: Nutzerdaten aktualisieren
ChoosePrompt text@Text: Wähle deinen Artikel, #{text}
SelectItem: Wähle deinen Artikel
CurrentAmount: Aktuelle Anzahl
NoItems: keine Getränke vorhanden
StockUp name@Text: Bestand von #{name} auffüllen
Fillup: Auffüllen
CashCheckOf date@String: Kassensturz vom #{date}
NotJson: Dies sind keine JSON daten
Upload: Sicherung hochladen
SelectFile: Datei auswählen
RestoreSuccess: Datenbankwiederherstellung erfolgreich!
InventoryBackup: Inventarsicherung herunterladen
RestoreFromBackup: Inventar wiederherstellen
NegativeRecharge: Keine negativen Beträge aufladen
Increment: ++
Decrement: --
Plus5: +=5
Minus5: -=5
SelectAvatar: Avatar auswählen
Avatars: Avatare
NoAvatars: Keine Avatare
ModifyAvatar: Avatar bearbeiten
AvatarUnknown: Unbekannter Avatar
AvatarUpdateSuccessfull: Avatar erfolgreich aktualisiert
AvatarIdent: Avatarname
AvatarFileChange: Datei auswählen um Avatar zu ändern
AvatarFile: Datei für den Avatar
NewAvatar: Neuer Avatar
AvatarUploadSuccessfull: Avatar erfolgreich hochgeladen
DeleteAvatar: Diesen Avatar löschen
AvatarDeleted: Avatar gelöscht
AvatarInUseError: Avatare können nicht gelöscht werden, solange sie in Benutzung sind.
Volume: Volumen in l
CorrectedAmount: Schwund
BarcodeNotUser: Dieser Barcode ist keinem Benutzer zugeordnet, sondern einem Produkt
ProvideBarcode: Bitte korrekten Barcode angeben
BarcodeNotBev: Dieser Barcode ist keinem Produkt zugeordnet, sondern einem Benutzer
BarcodeUnknown: Dieser Barcode ist unbekannt
BarcodeField: Barcodes
BarcodeAdded: Barcode erfolgreich hinzugefügt
BarcodeDuplicate: Dieser barcode wird schon verwendet
Transfer: Transferieren
TransferTo: Guthaben transferieren an
NegativeTransfer: Keine negativen Beträge transferieren
TransferComplete: Transfer abgeschlossen
TransferError: Fehler beim Transfer
PreviousPage: vorherige Seite
NextPage: nächste Seite
MaxAmount: Maximale Lagermenge
AmountPerCrate: Anzahl pro Kasten
SelectSupplier: Lieferanten wählen
CreateSupplier: Neuen Lieferanten anlegen
SupplierCreated: Neuer Lieferant wurde erstellt
SupplierNotCreated: Neuer Lieferant konnte nicht angelegt werden
Suppliers: Lieferanten
NewSupplier: Neuer Lieferant
Address: Adresse
TelNr: Telefonnummer
Email: Email
EditSupplier: Lieferanten bearbeiten
SupplierUnknown: Dieser Lieferant ist nicht bekannt
SupplierEdited: Lieferant wurde bearbeitet
SupplierNotEdited: Lieferant konnte nicht bearbeitet werden
CreateSupplierDigest: Bestellübersicht für diesen Lieferanten erstellen
DeleteSupplier: diesen Lieferanten löschen
SupplierDeleted: Lieferant erfolgreich gelöscht
SupplierInUseError: Dieser Lieferant wird noch von Produkten benutzt.
ArtNr: Artikelnummer
PricePerCrate: Preis Pro Kasten
CrateCount: Anzahl Kästen
BuyValue: Zahlbetrag
CustomerId: Kundennummer
TotalCrates: Gesamtanzahl Kästen
Modify: bearbeiten
UserIdentNotUnique: Benutzername ist nicht einzigartig
