UserReactivated: Kasutaja reaktiveeritud
UserUnknown: Tundmatu kasutaja
UserOrArticleUnknown: Kasutaja või toode tundmatu
PurchaseSuccess: Naudi!
PurchaseDebtful: Tähelepanu: Teil on völgnevus!
NotEnoughItems: Toode pole saadaval
ErrorOccured: Midagi läks valesti
ItemUnknown: Tundmatu toode
PurchaseSuccessCash price@Int currency@Text: Naudi. Palun sooritage makse #{currency} #{formatIntCurrency price} #{currency} sularahas.
ItemDisappeared: Toode läks kaduma o_0
Amount: Kogus
EditSuccess: Muudetud edukalt
EditFail: Muutmine ebaõnnestus
Name: Nimi		
Price: Hind
CurrentStock: hetke varu
AnnouncedStock: Warning limit
DeleteItem: Kustuta Toode
ItemDeleted: Toode kustutatud
UserCreated: kasutaja loodud
UserNotCreated: Ei saanud uut kasutajat luua
EmailNotify: teavituste saamiseks lisa email
BuyNotification: Teavita ostu puhul
UserEdited: Kasutaja muudetud
UserNotEdited: Ei saanud kasutajat muuta
Payout desc@Text: Väljamakse: #{desc}
PaidOut: Kogus väljamakstud
NotPaidOut: Ei saanud väljamakset teha
Value: Väärtus
Description: Kirjeldus
StockedUp: varud lisatud
NotStockedUp: Ei saanud varusid lisada
StockupError: Viga varude lisamisel
AmountAdded: üksikute toodete hulk lisatud
CrateAmountAdded: taarakastide hul lisatud
ItemAdded: Uus toode lisatud
AmountWarning: Koguse hoiatus
Recharged: Laetud!
RechargeError: Viga laadimisel
CashCheck: sularaha kontroll
CashChecked: Sularaha kontrollitud ja uuendatud
CashCheckError: Viga sularaha kontrollimisel
CountedValue: Loetud väärtus
PurchaseOf name@Text: Ostmine #{name}
PricePerUnit price@Int currency@Text: Hind ühiku kohta: #{currency} #{formatIntCurrency price}
Purchase: Osta
PleaseCountAndCheck: Palun kontrollige üle sularahavarud allpool.
Submit: Lisa
Home: Pealeht
Restock: Lae inventar
Journal: Arveraamat
Summary: Inventar
PayCash: Maksa sularaha
CreateUser: Loo kasutaja
ReactivateOldUser: reaktiveeri vana kasutaja
Time: Aeg
ValueIn currency@Text: Hind #{currency}
TotalValue: Koguhind
CashStock: sularaha varu
PayoutFromCash: Maksa välja sularaha
NothingToShow: Pole toiminguid tehtud
NewItem: Uus toode
NewUser: Uus kasutaja
DoPayout: Maksa välja
ReactivateUser: Taasta kasutaja
Recharge: Recharge
CurrentCharge charge@Int currency@Text: Current charge: #{currency} #{formatIntCurrency charge} #{currency}
AddItem: Lisa uus toode
EditUser: Muuda kasutajat
ChoosePrompt text@Text: Vali toode, #{text}
SelectItem: Valit toode
CurrentAmount: Hetke kogus
NoItems: Ei oole ühtegi toodet
StockUp name@Text: Lisa varusid #{name}
Fillup: Fill up
CashCheckOf date@String: Sula kontrollimine #{date}
NotJson: Andmed ei ole JSON formaadis
Upload: Lae üles varundusfail
SelectFile: Vali fail
RestoreSuccess: Andmebaas edukalt taastatud !
InventoryBackup: Varunda inventar
RestoreFromBackup: Taasta varundusfailist
NegativeRecharge: Ei saa taaslaadida negatiivseid summasid
Increment: ++
Decrement: --
Plus5: +=5
Minus5: -=5
SelectAvatar: Vali avatar
Avatars: Avatarid
NoAvatars: Pole avatare
ModifyAvatar: Muuda avatar
AvatarUnknown: Tundmatu avatar
AvatarUpdateSuccessfull: Avatar uuendatud !
AvatarIdent: Avatari nimi
AvatarFileChange: Avatari muutmiseks lisa fail
AvatarFile: Avatari kaust
NewAvatar: Uus avatar
AvatarUploadSuccessfull: Avatari üleslaadimine edukas !
DeleteAvatar: Kustuta avatar
AvatarDeleted: Avatar edukalt kustutatud
AvatarInUseError: Ei saa kustutada kasutusel olevaid avatare
Volume: Volume in l
CorrectedAmount: Loss
BarcodeNotUser: See vöötkood on kaup, mitte kasutaja
ProvideBarcode: Palun lisage õige vöötkood
BarcodeNotBev: See vöötkood on kasutaja, mitte kaup
BarcodeUnknown: Tundmatu vöötkood
BarcodeField: Vöötkoodid
BarcodeAdded: vöötkood edukalt lisatud
BarcodeDuplicate: See vöötkood on juba kasutusel
Transfer: krediteeri ülekanne
TransferTo: kanna krediit üle
NegativeTransfer: Negatiivseid summasid ei saa üle kanda
TransferComplete: Ülekanne sooritatud
TransferError: Viga ülekandel
MaxAmount: Max kogus
AmountPerCrate: kogus ostukorvi kohta
SelectSupplier: Vali tarnija
CreateSupplier: Loo tarnija
SupplierCreated: Tarnija loodud
SupplierNotCreated: Tarnijat ei loodud !
Suppliers: Tarnija
NewSupplier: Uus tarnija
Address: Aadress
TelNr: Telefoni number
Email: Email
EditSupplier: Muuda Tarnijat
SupplierUnknown: Tundmatu tarnija
SupplierEdited: Tarnija muudetud
SupplierNotEdited: Tarnijat ei muudetud!
CreateSupplierDigest: Loo tellimuse ülevaade selle tarnija kohta
DeleteSupplier: Kustuta tarnija
SupplierDeleted: Tarnija kustutatud
SupplierInUseError: Tarnija on veel kasutusel!
ArtNr: Artikli number
PricePerCrate: Hind ühe taarakasti kohta
CrateCount: taarakastide kogus
BuyValue: Makse summa
CustomerId: Kliendi ID
TotalCrates: taarakastide koguhulk
Modify: muuda
UserIdentNotUnique: Kasutajanimi ei ole unikaalne
Login: Logi sisse
Logout: Logi välja
CreationBlocked: Ei saa luua uut kasutajat.
NotEnoughFunds: Pole piisavalt raha !
