UserReactivated: User reactivated
UserUnknown: User unknown
UserOrArticleUnknown: User or item unknown
PurchaseSuccess: Enjoy!
PurchaseDebtful: Attention: You are in debt!
NotEnoughItems: Not enough items available
ErrorOccured: Something went wrong
ItemUnknown: Item unknown
PurchaseSuccessCash price@Int currency@Text: Enjoy. Please pay #{currency} #{formatIntCurrency price} #{currency} in cash.
ItemDisappeared: Item disappeared o_0
Amount: Amount
EditSuccess: Edited successfully
EditFail: Editing failed
Name: Name
Price: Price
CurrentStock: Current stock
AnnouncedStock: Announced stock
DeleteItem: Delete Item
ItemDeleted: Item deleted
UserCreated: User created
UserNotCreated: Could not create user
EmailNotify: enter eMail if you want notifications
BuyNotification: Notify on purchase
UserEdited: User edited
UserNotEdited: Could not edit user
Payout desc@Text: Payout: #{desc}
PaidOut: Amount paid out
NotPaidOut: Could not pay out
Value: Value
Description: Description
StockedUp: Stocked up
NotStockedUp: Could not stock up
StockupError: Error stocking up
AmountAdded: Amount added
ItemAdded: New item added
ItemNotAdded: Error when adding
AmountWarning: Amount warning
Recharged: Recharged!
RechargeError: Error recharging
CashCheck: Cash check
CashChecked: Cash checked and updated.
CashCheckError: Error on cash check
CountedValue: Counted value
PurchaseOf name@Text: Purchase of #{name}
PricePerUnit price@Int currency@Text: Price per unit: #{currency} #{formatIntCurrency price}
Purchase: Buy
PleaseCountAndCheck: Please count cash reserves and update amount below.
Submit: Submit
Home: Home
Restock: Restock inventory
Journal: Journal
Summary: Inventory
PayCash: Pay cash
CreateUser: Create user
ReactivateOldUser: Reactivate old user
Time: Time
ValueIn currency@Text: Value in #{currency}
TotalValue: Total value
CashStock: Cash stock
PayoutFromCash: Pay out cash
NothingToShow: No movements
NewItem: New item
NewUser: New User
DoPayout: Payout
ReactivateUser: Reactivate user
Recharge: Recharge
CurrentCharge charge@Int currency@Text: Current charge: #{currency} #{formatIntCurrency charge} #{currency}
AddItem: Add new item
EditUser: Edit user
ChoosePrompt text@Text: Choose an item, #{text}
SelectItem: Select item
CurrentAmount: Current amount
NoItems: No items
StockUp name@Text: Stock up #{name}
Fillup: Fill up
CashCheckOf date@String: Cash check of #{date}
