UserReactivated: User reactivated
UserUnknown: User unknown
UserOrArticleUnknown: User or item unknown
PurchaseSuccess: Enjoy!
PurchaseDebtful: Attention: You are in debt!
NotEnoughItems: Not enough items available
ErrorOccured: Something went wrong
ItemUnknown: Item unknown
PurchaseSuccessCash price@Int currency@Text: Enjoy. Please pay #{currency} #{formatIntCurrency price} #{currency} in cash.
ItemDisappeared: Item disappeared o_0
Amount: Amount
EditSuccess: Edited successfully
EditFail: Editing failed
Name: Name
Price: Price
CurrentStock: Current stock
AnnouncedStock: Announced stock
DeleteItem: Delete Item
ItemDeleted: Item deleted
UserCreated: User created
UserNotCreated: Could not create user
EmailNotify: enter eMail if you want notifications
BuyNotification: Notify on purchase
UserEdited: User edited
UserNotEdited: Could not edit user
Payout desc@Text: Payout: #{desc}
PaidOut: Amount paid out
NotPaidOut: Could not pay out
Value: Value
Description: Description
StockedUp: Stocked up
NotStockedUp: Could not stock up
StockupError: Error stocking up
AmountAdded: Amount added
ItemAdded: New item added
ItemNotAdded: Error when adding
AmountWarning: Amount warning
Recharged: Recharged!
RechargeError: Error recharging
CashCheck: Cash check
CashChecked: Cash checked and updated.
CashCheckError: Error on cash check
CountedValue: Counted value
PurchaseOf name@Text: Purchase of #{name}
PricePerUnit price@Int currency@Text: Price per unit: #{currency} #{formatIntCurrency price}
Purchase: Buy
PleaseCountAndCheck: Please count cash reserves and update amount below.
Submit: Submit
Home: Home
Restock: Restock inventory
Journal: Journal
Summary: Inventory
PayCash: Pay cash
CreateUser: Create user
ReactivateOldUser: Reactivate old user
Time: Time
ValueIn currency@Text: Value in #{currency}
TotalValue: Total value
CashStock: Cash stock
PayoutFromCash: Pay out cash
NothingToShow: No movements
NewItem: New item
NewUser: New User
DoPayout: Payout
ReactivateUser: Reactivate user
Recharge: Recharge
CurrentCharge charge@Int currency@Text: Current charge: #{currency} #{formatIntCurrency charge} #{currency}
AddItem: Add new item
EditUser: Edit user
ChoosePrompt text@Text: Choose an item, #{text}
SelectItem: Select item
CurrentAmount: Current amount
NoItems: No items
StockUp name@Text: Stock up #{name}
Fillup: Fill up
CashCheckOf date@String: Cash check of #{date}
NotJson: These are not JSON data
Upload: Upload backup
SelectFile: Select file
RestoreSuccess: Database restored successfully!
InventoryBackup: Backup inventory
RestoreFromBackup: Restore from backup
NegativeRecharge: You can not recharge negative amounts
Increment: ++
Decrement: --
Plus5: +=5
Minus5: -=5
SelectAvatar: Select avatar
Avatars: Avatars
NoAvatars: No avatars
ModifyAvatar: Modify avatar
AvatarUnknown: Avatar unknown
AvatarUpdateSuccessfull: Avatar update successfull
AvatarIdent: Avatar name
AvatarFileChange: Enter file to change this avatar
AvatarFile: Avatar file
NewAvatar: New avatar
AvatarUploadSuccessfull: Avatar upload successfull
DeleteAvatar: Delete avatar
AvatarDeleted: Avatar successfully deleted
AvatarInUseError: You can not delete avatars that are currently in use
Volume: Volume in l
CorrectedAmount: Loss
BarcodeNotUser: This barcode is no user, but a product
ProvideBarcode: Please provide a correct barcode
BarcodeNotBev: This barcode is no product, but a user
BarcodeUnknown: This barcode is unknown
BarcodeField: Barcodes
BarcodeAdded: barcode succesfully added
BarcodeDuplicate: This barcode is already in use
Transfer: Credit transfer
TransferTo: Transfer credit to
NegativeTransfer: Please do not transfer negative amounts
TransferComplete: Transfer complete
TransferError: Transfer error
PreviousPage: previous page
NextPage: next page
MaxAmount: Max amount
AmountPerCrate: Amount per crate
SelectSupplier: Select supplier
CreateSupplier: Create supplier
SupplierCreated: Supplier created
SupplierNotCreated: Supplier not created!
Suppliers: Suppliers
NewSupplier: new Supplier
Address: Adress
TelNr: Telephone number
Email: Email
EditSupplier: Edit Supplier
SupplierUnknown: Supplier unknown
SupplierEdited: Supplier edited
SupplierNotEdited: Supplier not edited!
CreateSupplierDigest: Create order overview for this supplier
DeleteSupplier: Delete this Supplier
SupplierDeleted: Supplier successfully deleted
SupplierInUseError: This supplier is still in use!
ArtNr: Article number
PricePerCrate: Price per Crate
CrateCount: Crate count
BuyValue: Payment amount
CustomerId: Customer id
TotalCrates: Total crates
Modify: modify
UserIdentNotUnique: Username is not unique
