UserReactivated: Compte réactivé
UserUnknown: Compte inconnu
UserOrArticleUnknown: Compte ou chose inconnu
PurchaseSuccess: Savourez !
PurchaseDebtful: Attention: vous avez fait des dettes !
NotEnoughItems: insuffisante quantité des choses
ErrorOccured: Oups
ItemUnknown: Chose inconnue
PurchaseSuccessCash price@Int currency@Text: Savourez ! S'il-vous plaît payez #{currency} #{formatIntCurrency price} #{currency} en espèces .
ItemDisappeared: Chose disapparue o_0
Amount: Quantité
EditSuccess: Martelé avec succès
EditFail: Marteler avec échec
Name: Nom
Price: Prix
CurrentStock: Fonds actuel
AnnouncedStock: Fonds communiqué
DeleteItem: Annuler chose
ItemDeleted: Chose annulée
UserCreated: Compte édifié
UserNotCreated: Impossible de édifier un compte
BuyNotification: Notification de achat
UserEdited: Compte martelé
UserNotEdited: Impossible de modifier compte
Payout desc@Text: Décaissement : #{desc}
PaidOut: Quantité décaissé
NotPaidOut: Impossible de décaisser
Value: Valeur
Description: Description
StockedUp: Provisionné
NotStockedUp: Pas provisionné
StockupError: Erreur !
AmountAdded: Quantité ajouté
ItemAdded: Chose ajoutée
ItemNotAdded: Pas ajouté
AmountWarning: Attention de quantité
Recharged: Chargé
RechargeError: Erreur de charger
CashCheck: Contrôle de caisse
CashChecked: Caisse contrôlé et à jour
CashCheckError: Erreur de contrôle de caisse
CountedValue: Valeur comptée
PurchaseOf name@Text: Achat de #{name}
PricePerUnit price@Int currency@Text: Prix à l'unité: #{currency} #{formatIntCurrency price}
Purchase: Achète
PleaseCountAndCheck: S'il-vous plaît compter et inscrire dessous.
Submit: Envoyer
Home: Accueil
Restock: Provisionner inventaire
Journal: Journal
Summary: Résumé
PayCash: Payer rubis sur l'ongle
CreateUser: Edifier compte
ReactivateOldUser: Reactiver compte vieil
Time: Temps
ValueIn currency@Text: Valeur en #{currency}
TotalValue: Valeur totale
CashStock: La encaisse
PayoutFromCash: Versement en liquide
NothingToShow: Rien des mouvements
NewItem: Nouvelle chose
NewUser: Nouveau compte
DoPayout: Decaisser
ReactivateUser: Reactiver compte
Recharge: Charger
CurrentCharge charge@Int currency@Text: Montant actuel: #{currency} #{formatIntCurrency charge} #{currency}
AddItem: Ajouter une chose
EditUser: Modifier compte
ChoosePrompt text@Text: Faites un choix , #{text}
SelectItem: Sélectionnes quelque chose
CurrentAmount: Quantité actuel
NoItems: Pas de choses
StockUp name@Text: Provisionner de #{name}
Fillup: Remplir
CashCheckOf date@String: Contrôle de caisse de #{date}
NotJson: Ceci n'est pas états JSON
Upload: Télécharger sécurisation
SelectFile: Choisir un fichier
RestoreSuccess: Banque de données établi
InventoryBackup: Télécharger de sécurisation
RestoreFromBackup: Reconstituer une sécurisation
NegativeRecharge: Ne pas charger les valeurs opposées
Increment: ++
Decrement: --
Plus5: +=5
Minus5: -=5
