UserReactivated: Korisnik reaktiviran 
UserUnknown: Korisnik nepoznat
UserOrArticleUnknown: Korisnik ili artikal nepoznati 
PurchaseSuccess: Uživaj!
PurchaseDebtful: Pozor: U dugu si! 
NotEnoughItems: Nedovoljno raspoloživih artikala
ErrorOccured: Nešto je pošlo ukrivo
ItemUnknown: Nepoznati artikal 
PurchaseSuccessCash price@Int currency@Text: Uživaj. Molimo platite #{currency} #{formatIntCurrency price} #{currency} u gotovini.
ItemDisappeared: Artikal je nestao o_0
Amount: Količina
EditSuccess: Uređivanje uspješno 
EditFail: Uređivanje neuspješno
Name: Ime
Price: Cijena
CurrentStock: Trenutne zalihe 
AnnouncedStock: Objavljene zalihe
DeleteItem: Obriši artikal
ItemDeleted: Artikal obrisan
UserCreated: Korisnik stvoren
UserNotCreated: Nije moguće stvoriti korisnika 
EmailNotify: Unesite Email ako želite primati obavijesti 
BuyNotification: Obavijest o kupnji 
UserEdited: Korisnik uređen
UserNotEdited: Nije moguće urediti korisnika
Payout desc@Text: Isplata: #{desc}
PaidOut: Iznos isplaćen
NotPaidOut: Nemogučnost isplate
Value: Vrijednost
Description: Opis
StockedUp: Opskrbljeno
NotStockedUp: Nemogučnost opskrbe
StockupError: Greška u opskrbi
AmountAdded: Amount of single items added / Količina dodanih pojedinačnih artikala 
CrateAmountAdded: Količina dodanih sanduka
ItemAdded: Novi artikal dodan
ItemNotAdded: Pogreška u dodavanju
AmountWarning: Količinsko upozorenje
Recharged: Napunjeno!
RechargeError: Pogreška kod punjenja
CashCheck: Provjera gotovine
CashChecked: Gotovina provjerena i ažurirana.
CashCheckError: Pogreška kod provjere gotovine
CountedValue: Izbrojana vrijednost
PurchaseOf name@Text: Kupovina artikla #{name}
PricePerUnit price@Int currency@Text: Cijena po komadu: #{currency} #{formatIntCurrency price}
Purchase: Kupi
PleaseCountAndCheck: Molimo da prebrojite zalihe gotovine i ažurirajte donji iznos.
Submit: Podnesi
Home: Početak
Restock: Popunjavanje inventara 
Journal: Dnevnik
Summary: Inventar
PayCash: Plati gotovinu
CreateUser: Stvori korisnika
ReactivateOldUser: Reaktiviraj starog korisnika
Time: Vrijeme
ValueIn currency@Text: Vrijednost u #{currency} 
TotalValue: Ukupna vrijednost
CashStock: Zaliha gotovine
PayoutFromCash: Plati u gotovini
NothingToShow: Nema zbivanja
NewItem: Novi artikal
NewUser: Novi korisnik
DoPayout: Isplata
ReactivateUser: Reaktiviraj korisnika 
Recharge: Napuniti
CurrentCharge charge@Int currency@Text: Trenutna naplata: #{currency} #{formatIntCurrency charge} #{currency} 
AddItem: Dodaj novi artikal 
EditUser: Uredi korisnika
ChoosePrompt text@Text: Odaberi artikal, #{text}
SelectItem: Izaberi artikal
CurrentAmount: Trenutni iznos
NoItems: Nema artikala
StockUp name@Text: Opskrbi #{name}
Fillup: Ispuni
CashCheckOf date@String: Provjera gotovine od #{date} 
NotJson: Ovo nisu JSON podaci 
Upload: Napravi sigurnosnu kopiju
SelectFile: Izaberi datoteku
RestoreSuccess: Baza podataka obnovljena uspješno! 
InventoryBackup: Sigurnosna kopija inventara
RestoreFromBackup: Vrati iz sigurnosne kopije
NegativeRecharge: Ne možete napuniti negativne iznose.
Increment: ++ 
Decrement: -- 
Plus5: +=5 
Minus5: -=5 
SelectAvatar: Izaberi avatara 
Avatars: Avatari
NoAvatars: Bez avatara
ModifyAvatar: Izmjeni avatara
AvatarUnknown: Avatar nepoznat
AvatarUpdateSuccessfull: Ažuriranje avatara uspješno 
AvatarIdent: Ima avatara
AvatarFileChange: Unesi datoteku kako bi promijenio ovog avatara 
AvatarFile: Avatar datoteka 
NewAvatar: Novi avatar
AvatarUploadSuccessfull: Unos avatara uspješan
DeleteAvatar: Izbriši avatara
AvatarDeleted: Avatar uspješno izbrisan
AvatarInUseError: Ne možete izbrisati avatare koji su trenutno u upotrebi 
Volume: Volumen u l
CorrectedAmount: Gubitak
BarcodeNotUser: Ovaj barkod nije korisnik nego proizvod
ProvideBarcode: Molimo podnesite ispravan barkod
BarcodeNotBev: Ovaj barkod nije proizvod nego korisnik
BarcodeUnknown: Ovaj barkod je nepoznat 
BarcodeField: Barkodovi
BarcodeAdded: barkod uspješno dodan 
BarcodeDuplicate: Ovaj barkod je već u upotrebi
Transfer: Prijenos kredita
TransferTo: Prenesi kredit na
NegativeTransfer: Molimo nemojte prenositi negativne iznose 
TransferComplete: Prijenos dovršen 
TransferError: Prijenosna greška
PreviousPage: prethodna stranica
NextPage: sljedeća stranica
MaxAmount: Maksimalni iznos
AmountPerCrate: Iznos po sanduku
SelectSupplier: Odaberi dobavljača
CreateSupplier: Stvori dobavljača
SupplierCreated: Dobavljač stvoren
SupplierNotCreated: Dobavljač nije stvoren!
Suppliers: SDobavljači
NewSupplier: novi Dobavljač
Address: Adresa
TelNr: Telefonski broj
Email: Email
EditSupplier: Uredi Dobavljača 
SupplierUnknown: Dobavljač nepoznat
SupplierEdited: Dobavljač uređen
SupplierNotEdited: Dobavljač nije uređen!
CreateSupplierDigest: Stvori pregled naruđbe za ovog dobavljača
DeleteSupplier: Izbriši ovog Dobavljača 
SupplierDeleted: Dobavljač uspješno izbrisan
SupplierInUseError: Ovaj dobavljač je još u upotrebi!
ArtNr: Broj artikla
PricePerCrate: Cijena po Sanduku 
CrateCount: Broj sanduka
BuyValue: Platni iznos
CustomerId: Korisnikov id 
TotalCrates: Ukupno sanduka
Modify: izmijeniti
UserIdentNotUnique: Koriničko ime nije jedinstveno 
