UserReactivated: użytkownik włączony
UserUnknown: użytkownik nieznany
UserOrArticleUnknown: użytkownik lub artykuł nieznany
PurchaseSuccess: na zdrowie!
PurchaseDebtful: uwaga: masz minus
NotEnoughItems: za mało sztuk
ErrorOccured: coś poszło nie tak
ItemUnknown: artykuł nieznany
PurchaseSuccessCash price@Int currency@Text: na zdrowie! prosimy o dokonanie wpłaty #{formatIntCurrency price} #{currency} gotówką
ItemDisappeared: artykuł zniknął o_0
Amount: liczba
EditSuccess: przetwarzanie powiodło się
EditFail: przetwarzanie nie jest możliwe
Name: nazwa
Price: cena
CurrentStock: aktualny wybór
AnnouncedStock: wybór ogłoszony
DeleteItem: usuń artykuł
ItemDeleted: artykuł usunięty
UserCreated: użytkownik utworzony
UserNotCreated: użytkownik nie może być utworzony
EmailNotify: podaj e-mail jeśli chcesz otrzymywać powiadomienia
BuyNotification: powiadomienie przy zakupie
UserEdited: zaktualizowano dane użytkownika
UserNotEdited: aktualizacja danych użytkownika nie powiodła się
Payout desc@Text: wypłata: #{desc}
PaidOut: kwota wypłacona
NotPaidOut: wypłata nie jest możliwa
Value: należność
Description: opis
StockedUp: zapas uzupełniony
NotStockedUp: zapas nieuzupełniony
StockupError: błąd uzupełniania zapasu
AmountAdded: dodana ilość
ItemAdded: artykuł dodany
ItemNotAdded: błąd dodawania
AmountWarning: ostrzeżenie: ilość
Recharged: doładowano
RechargeError: błąd w doładowaniu
CashCheck: podlicz kasę
CashChecked: kasa podliczona i zaktualizowana
CashCheckError: błąd podliczania
CountedValue: kwota naliczona
PurchaseOf name@Text: zakup #{name}
PricePerUnit price@Int currency@Text: cena za sztukę: #{formatIntCurrency price} #{currency}
Purchase: zakup
PleaseCountAndCheck: podlicz należność i wynik wpisz w polu poniżej
Submit: wyślij
Home: strona główna
Restock: uzupełnij inwentarz
Journal: czasopismo
Summary: inwentarz
PayCash: płatność gotówką
CreateUser: utworz użytkownika
ReactivateOldUser: włącz istniejącego użytkownika
Time: czas
ValueIn currency@Text: należność w #{currency}
TotalValue: całkowita należność
CashStock: dostępna gotówka
PayoutFromCash: zapłać z kasy
NothingToShow: brak ruchu
NewItem: nowy artykuł
NewUser: nowy użytkownik
DoPayout: wypłać
ReactivateUser: włącz użytkownika
Recharge: uzupełnij kredyt
CurrentCharge charge@Int currency@Text: saldo bieżące: #{formatIntCurrency charge} #{currency}
AddItem: dodaj nowy artykuł
EditUser: aktualizacja danych użytkownika
ChoosePrompt text@Text: wybierz artykuł, #{text}
SelectItem: wybierz artykuł
CurrentAmount: aktualna ilość
NoItems: brak towaru
StockUp name@Text: w tym: #{name} wpisz nazwę
Fillup: wypełnij
CashCheckOf date@String: podliczenie kasy z dn. #{date}
NotJson: to nie JSON data
Upload: wyślij kopię zapasową
SelectFile: wybierz plik
RestoreSuccess: baza danych pomyślnie przywrócona!
InventoryBackup: kopia zapasowa inwentarza
RestoreFromBackup: przywróć z kopii zapasowej
NegativeRecharge: You can not recharge negative amounts
Increment: ++
Decrement: --
SelectAvatar: SelectAvatar
NoAvatars: No avatars
ModifyAvatar: Modify avatar
