UserReactivated: wyłączony użytkownika
UserUnknown: nieznany użytkownik
UserOrArticleUnknown: Użytkownik lub artykuły nieznane
PurchaseSuccess: świetna zabawa
PurchaseDebtful: uważaj kredyty ostrożność w minusie
NotEnoughItems: tak wiele rzeczy nie są dostępne
ErrorOccured: coś poszło nie tak
ItemUnknown: Artykuły nieznane
PurchaseSuccessCash price@Int currency@Text: świetna zabawa. prosimy o dokonanie wpłaty #{formatIntCurrency price} #{currency} na fundusz
ItemDisappeared: artykuł zniknął o_0
Amount: liczba
EditSuccess: przetwarzanie powodzeniem
EditFail: przetwarzanie nie jest możliwe
Name: nazwa
Price: cena
CurrentStock: obecny był
AnnouncedStock: Zmień kolejność
DeleteItem: usunięcie artykułu
ItemDeleted: usunięte elementy
UserCreated: utworzyć użytkownika
UserNotCreated: Użytkownik nie może być utworzony
EmailNotify: Podaj e-mail powiadomienia w razie potrzeby
BuyNotification: powiadomienie na zakup
UserEdited: aktualizacja danych użytkownika
UserNotEdited: Aktualizacja danych użytkownika nie powiodło się
Payout desc@Text: wypłaty: #{desc}
PaidOut: kwota wypłacona
NotPaidOut: Wypłata nie jest możliwe
Value: należność
Description: opis
StockedUp: Uzupełniania zapasów
NotStockedUp: Zdjęcie nie może być ujemna wypełnione
StockupError: błąd podczas napełniania
AmountAdded: dodany numer
ItemAdded: Dodano nowy artykuł
ItemNotAdded: Błąd podczas dodawania
AmountWarning: ostrzeżenie w liczbie
Recharged: kredyty powodzeniem pobierana
RechargeError: Podczas ładowania błędów
CashCheck: fundusze spaść
CashChecked: Kassensturz wykonania. Zaktualizowany Zamówienie
CashCheckError: błąd
CountedValue: kwota wypłacona
PurchaseOf name@Text: zakup #{name}
PricePerUnit price@Int currency@Text: Cena za sztukęt: #{formatIntCurrency price} #{currency}
Purchase: kupić
PleaseCountAndCheck: Proszę to kasy i wpisać kwotę zapłaconą w polu poniżej.
Submit: wysłać
Home: strona główna
Restock: uzupełnić
Journal: czasopismo
Summary: inwentarz
PayCash: płacić gotówką
CreateUser: Tworzenie nowego użytkownika
ReactivateOldUser: Wyłącz stary użytkownika
Time: czas
ValueIn currency@Text: wynieść się #{currency}
TotalValue: Całkowita ilość
CashStock: gotówka
PayoutFromCash: Zapłać z funduszu
NothingToShow: Nie zarejestrowane ruchy
NewItem: Nowy artykuł
NewUser: Nowy użytkownik
DoPayout: Wypłata
ReactivateUser: Wyłącz użytkownika
Recharge: Naładuj kredytowej
CurrentCharge charge@Int currency@Text: saldo bieżące: #{formatIntCurrency charge} #{currency}
AddItem: Dodaj nową pozycję
EditUser: Aktualizacja danych użytkownika
ChoosePrompt text@Text: Wybierz swój artykuł, #{text}
SelectItem: Wybierz swój artykuł
CurrentAmount: Aktualny numer
NoItems: Napoje dostępne żadne
StockUp name@Text: składało się z #{name} wypełnić
Fillup: wypełnić
CashCheckOf date@String: Fundusze spaść z #{date}
