UserReactivated: Korisnik ponovo aktiviran 
UserUnknown: Nepoznat korisnik
UserOrArticleUnknown: Korisnik ili stavka nepoznati
PurchaseSuccess: Uživajte!
PurchaseDebtful: Pažnja: U dugu ste!
NotEnoughItems: Nema dovoljno dostupnih stavki 
ErrorOccured: Nastala je greška
ItemUnknown: Nepoznata stavka
PurchaseSuccessCash price@Int currency@Text: Uživajte. Molimo Vas, platite #{currency} #{formatIntCurrency price} #{currency} u kešu.
ItemDisappeared: Stavka je nestala
Amount: Iznos
EditSuccess: Uspešno prepravljeno
EditFail: Ispravka nije uspela
Name: Ime
Price: Cena
CurrentStock: Trenutne zalihe
AnnouncedStock: Najavljene zalihe
DeleteItem: Izbrisati stavku
ItemDeleted: Stavka izbrisana
UserCreated: Korisnik kreiran
UserNotCreated: Korisnik nije uspešno kreiran
EmailNotify: Unesite email ako želite obaveštenja 
BuyNotification: Obaveštenje o kupovini 
UserEdited: Korisnik promenjen
UserNotEdited: Korisnik nije promenjen
Payout desc@Text: Isplata: #{desc}
PaidOut: Iznos isplaćen
NotPaidOut: Plaćanje nije izvršeno
Value: Vrednost
Description: Opis
StockedUp: Na zalihama
NotStockedUp: Nema na zalihama
StockupError: Greška u zalihama
AmountAdded: Količina dodatih pojedinačnih stavki
CrateAmountAdded: Količina dodatih sanduka 
ItemAdded: Nova stavka dodata
ItemNotAdded: Greška prilikom dodavanja
AmountWarning: Upozorenje o količini
Recharged: Dopunjeno!
RechargeError: Greška u dopunjavanju
CashCheck: Provera keša
CashChecked: Keš proveren i ažuriran
CashCheckError: Greška u proveri keša
CountedValue: Uračunata vrednost
PurchaseOf name@Text: Kupovina #{name}
PricePerUnit price@Int currency@Text: Cena po jedinici #{currency} #{formatIntCurrency price}
Purchase: Kupovina
PleaseCountAndCheck: Molimo vas, prebrojte keš i ažurirajte iznos ispod. 
Submit: Prihvati
Home: Početna strana
Restock: Inventar dopunjavanja zaliha
Journal: Časopis
Summary: Rezime
PayCash: Platiti u kešu
CreateUser: Kreirati korisnika 
ReactivateOldUser: Ponovo aktivirati starog korisnika
Time: Vreme
ValueIn currency@Text: Vrednost u #{currency}
TotalValue: Ukupna vrednost
CashStock: Zalihe keša
PayoutFromCash: Isplata u kešu
NothingToShow: Nema promena
NewItem: Nova stavka
NewUser: Novi korisnik
DoPayout: Isplata
ReactivateUser: Ponovno aktiviranje korisnika
Recharge: Dopuna
CurrentCharge charge@Int currency@Text: Trenutna naplata: #{currency} #{formatIntCurrency charge} #{currency}
AddItem: Dodati novu stavku
EditUser: Izmeniti korisnika
ChoosePrompt text@Text: Izaberi stavku, #{text}
SelectItem: Odabrati stavku
CurrentAmount: Trenutni iznos
NoItems: Nema stavki
StockUp name@Text: Povećati zalihe #{name}
Fillup: Dopuniti
CashCheckOf date@String: Račun od #{date}
NotJson: Ne postoje JSON podaci 
Upload: Rezervna otprema
SelectFile: Izabrati stavku
RestoreSuccess: Baza podataka uspešno vraćena. 
InventoryBackup: Rezervni inventar
RestoreFromBackup: Povratiti iz rezervi
NegativeRecharge: Ne možete dopuniti negativne iznose 
Increment: ++
Decrement: --
Plus5: +=5
Minus5: -=5
SelectAvatar: Izaberite avatar
Avatars: Avatari
NoAvatars: Nema avatara
ModifyAvatar: Prepraviti avatar
AvatarUnknown: Nepoznat avatar
AvatarUpdateSuccessfull: Ažuriranje avatara uspešno
AvatarIdent: Naziv avatara
AvatarFileChange: Unesite stavku kako biste promenili avatar
AvatarFile: Avatar dokument
NewAvatar: Novi avatar
AvatarUploadSuccessfull: Učitavanje avatara uspešno
DeleteAvatar: Izbrisati avatar
AvatarDeleted: Avatar uspešno izbrisan
AvatarInUseError: Ne možete izbrisati avatare koje trenutno koristite
Volume: Količina u l
CorrectedAmount: Gubitak
BarcodeNotUser: Ovaj bar-kod nije korisnik, već je proizvod
ProvideBarcode: Molimo Vas, unesite ispravan bar-kod
BarcodeNotBev: Ovaj bar-kod nije proizvod, već je korisnik
BarcodeUnknown: Ovaj bar-kod ne nepoznat
BarcodeField: Bar-kodovi
BarcodeAdded: Bar-kod uspešno dodat
BarcodeDuplicate: Ovaj bar-kod je već u upotrebi
Transfer: Transfer kredita
TransferTo: Preneti kredit 
NegativeTransfer: Ne možete prebaciti negativne iznose
TransferComplete: Transfer završen
TransferError: Greška u transferu
PreviousPage: Prethodna strana
NextPage: Sledeća strana
MaxAmount: Maksimalni iznos
AmountPerCrate: Iznos po sanduku
SelectSupplier: Odabrati dobavljača
CreateSupplier: Kreirati dobavljača
SupplierCreated: Dobavljač kreiran
SupplierNotCreated: Dobavljač nije kreiran!
Suppliers: Dobavljači
NewSupplier: Novi dobavljač
Address: Adresa
TelNr: Broj telefona
Email: Email
EditSupplier: Izmeniti dobavljača
SupplierUnknown: Nepoznat dobavljač
SupplierEdited: Dobavljač izmenjen
SupplierNotEdited: Dobavljač nije izmenjen!
CreateSupplierDigest: Kreirati utiske o porudžbini za ovog dobavljača 
DeleteSupplier: Obrisati ovog dobavljača
SupplierDeleted: Dobavljač uspešno obrisan
SupplierInUseError: Ovaj dobavljač je još uvek u upotrebi!
ArtNr: Broj stavke
PricePerCrate: Cena po sanduku
CrateCount: Broj sanduka
BuyValue: Iznos za isplatu
CustomerId: ID korisnika
TotalCrates: Ukupno sanduka
Modify: Ispraviti
UserIdentNotUnique: Korisničko ime nije jedinstveno
Login: Prijaviti se
Logout: Odjaviti se
CreationBlocked: Novi korisnici ne mogu biti kreirani
NotEnoughFunds: Nemate dovoljno novca!
